package fr.gbourquet.catnotab.dao.auto;

import fr.gbourquet.catnotab.serveur.metier.auto.DroitPersonneExample;
import fr.gbourquet.catnotab.serveur.metier.auto.DroitPersonneKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DroitPersonneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int countByExample(DroitPersonneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int deleteByExample(DroitPersonneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int deleteByPrimaryKey(DroitPersonneKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int insert(DroitPersonneKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int insertSelective(DroitPersonneKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    List<DroitPersonneKey> selectByExample(DroitPersonneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int updateByExampleSelective(@Param("record") DroitPersonneKey record, @Param("example") DroitPersonneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int updateByExample(@Param("record") DroitPersonneKey record, @Param("example") DroitPersonneExample example);
}