package fr.gbourquet.catnotab.dao.auto;

import fr.gbourquet.catnotab.serveur.metier.auto.Personne;
import fr.gbourquet.catnotab.serveur.metier.auto.PersonneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int countByExample(PersonneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int deleteByExample(PersonneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int insert(Personne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int insertSelective(Personne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    List<Personne> selectByExample(PersonneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    Personne selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int updateByExampleSelective(@Param("record") Personne record, @Param("example") PersonneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int updateByExample(@Param("record") Personne record, @Param("example") PersonneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int updateByPrimaryKeySelective(Personne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    int updateByPrimaryKey(Personne record);
}