package fr.gbourquet.catnotab.serveur.metier.auto;

import java.io.Serializable;

public class DroitPersonneKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catnotab.droit_utilisateur.codedroit
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    private String codedroit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catnotab.droit_utilisateur.idutilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    private Integer idutilisateur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catnotab.droit_utilisateur.codedroit
     *
     * @return the value of catnotab.droit_utilisateur.codedroit
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public String getCodedroit() {
        return codedroit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catnotab.droit_utilisateur.codedroit
     *
     * @param codedroit the value for catnotab.droit_utilisateur.codedroit
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public void setCodedroit(String codedroit) {
        this.codedroit = codedroit == null ? null : codedroit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catnotab.droit_utilisateur.idutilisateur
     *
     * @return the value of catnotab.droit_utilisateur.idutilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public Integer getIdutilisateur() {
        return idutilisateur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catnotab.droit_utilisateur.idutilisateur
     *
     * @param idutilisateur the value for catnotab.droit_utilisateur.idutilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public void setIdutilisateur(Integer idutilisateur) {
        this.idutilisateur = idutilisateur;
    }
}