package fr.gbourquet.catnotab.serveur.metier.auto;

import java.util.ArrayList;
import java.util.List;

public class DroitPersonneExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public DroitPersonneExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodedroitIsNull() {
            addCriterion("codedroit is null");
            return (Criteria) this;
        }

        public Criteria andCodedroitIsNotNull() {
            addCriterion("codedroit is not null");
            return (Criteria) this;
        }

        public Criteria andCodedroitEqualTo(String value) {
            addCriterion("codedroit =", value, "codedroit");
            return (Criteria) this;
        }

        public Criteria andCodedroitNotEqualTo(String value) {
            addCriterion("codedroit <>", value, "codedroit");
            return (Criteria) this;
        }

        public Criteria andCodedroitGreaterThan(String value) {
            addCriterion("codedroit >", value, "codedroit");
            return (Criteria) this;
        }

        public Criteria andCodedroitGreaterThanOrEqualTo(String value) {
            addCriterion("codedroit >=", value, "codedroit");
            return (Criteria) this;
        }

        public Criteria andCodedroitLessThan(String value) {
            addCriterion("codedroit <", value, "codedroit");
            return (Criteria) this;
        }

        public Criteria andCodedroitLessThanOrEqualTo(String value) {
            addCriterion("codedroit <=", value, "codedroit");
            return (Criteria) this;
        }

        public Criteria andCodedroitLike(String value) {
            addCriterion("codedroit like", value, "codedroit");
            return (Criteria) this;
        }

        public Criteria andCodedroitNotLike(String value) {
            addCriterion("codedroit not like", value, "codedroit");
            return (Criteria) this;
        }

        public Criteria andCodedroitIn(List<String> values) {
            addCriterion("codedroit in", values, "codedroit");
            return (Criteria) this;
        }

        public Criteria andCodedroitNotIn(List<String> values) {
            addCriterion("codedroit not in", values, "codedroit");
            return (Criteria) this;
        }

        public Criteria andCodedroitBetween(String value1, String value2) {
            addCriterion("codedroit between", value1, value2, "codedroit");
            return (Criteria) this;
        }

        public Criteria andCodedroitNotBetween(String value1, String value2) {
            addCriterion("codedroit not between", value1, value2, "codedroit");
            return (Criteria) this;
        }

        public Criteria andIdutilisateurIsNull() {
            addCriterion("idutilisateur is null");
            return (Criteria) this;
        }

        public Criteria andIdutilisateurIsNotNull() {
            addCriterion("idutilisateur is not null");
            return (Criteria) this;
        }

        public Criteria andIdutilisateurEqualTo(Integer value) {
            addCriterion("idutilisateur =", value, "idutilisateur");
            return (Criteria) this;
        }

        public Criteria andIdutilisateurNotEqualTo(Integer value) {
            addCriterion("idutilisateur <>", value, "idutilisateur");
            return (Criteria) this;
        }

        public Criteria andIdutilisateurGreaterThan(Integer value) {
            addCriterion("idutilisateur >", value, "idutilisateur");
            return (Criteria) this;
        }

        public Criteria andIdutilisateurGreaterThanOrEqualTo(Integer value) {
            addCriterion("idutilisateur >=", value, "idutilisateur");
            return (Criteria) this;
        }

        public Criteria andIdutilisateurLessThan(Integer value) {
            addCriterion("idutilisateur <", value, "idutilisateur");
            return (Criteria) this;
        }

        public Criteria andIdutilisateurLessThanOrEqualTo(Integer value) {
            addCriterion("idutilisateur <=", value, "idutilisateur");
            return (Criteria) this;
        }

        public Criteria andIdutilisateurIn(List<Integer> values) {
            addCriterion("idutilisateur in", values, "idutilisateur");
            return (Criteria) this;
        }

        public Criteria andIdutilisateurNotIn(List<Integer> values) {
            addCriterion("idutilisateur not in", values, "idutilisateur");
            return (Criteria) this;
        }

        public Criteria andIdutilisateurBetween(Integer value1, Integer value2) {
            addCriterion("idutilisateur between", value1, value2, "idutilisateur");
            return (Criteria) this;
        }

        public Criteria andIdutilisateurNotBetween(Integer value1, Integer value2) {
            addCriterion("idutilisateur not between", value1, value2, "idutilisateur");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 29 10:14:35 CEST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table catnotab.droit_utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}