package fr.gbourquet.catnotab.serveur.metier.auto;

import java.util.ArrayList;
import java.util.List;

public class PersonneExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public PersonneExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLoginIsNull() {
            addCriterion("login is null");
            return (Criteria) this;
        }

        public Criteria andLoginIsNotNull() {
            addCriterion("login is not null");
            return (Criteria) this;
        }

        public Criteria andLoginEqualTo(String value) {
            addCriterion("login =", value, "login");
            return (Criteria) this;
        }

        public Criteria andLoginNotEqualTo(String value) {
            addCriterion("login <>", value, "login");
            return (Criteria) this;
        }

        public Criteria andLoginGreaterThan(String value) {
            addCriterion("login >", value, "login");
            return (Criteria) this;
        }

        public Criteria andLoginGreaterThanOrEqualTo(String value) {
            addCriterion("login >=", value, "login");
            return (Criteria) this;
        }

        public Criteria andLoginLessThan(String value) {
            addCriterion("login <", value, "login");
            return (Criteria) this;
        }

        public Criteria andLoginLessThanOrEqualTo(String value) {
            addCriterion("login <=", value, "login");
            return (Criteria) this;
        }

        public Criteria andLoginLike(String value) {
            addCriterion("login like", value, "login");
            return (Criteria) this;
        }

        public Criteria andLoginNotLike(String value) {
            addCriterion("login not like", value, "login");
            return (Criteria) this;
        }

        public Criteria andLoginIn(List<String> values) {
            addCriterion("login in", values, "login");
            return (Criteria) this;
        }

        public Criteria andLoginNotIn(List<String> values) {
            addCriterion("login not in", values, "login");
            return (Criteria) this;
        }

        public Criteria andLoginBetween(String value1, String value2) {
            addCriterion("login between", value1, value2, "login");
            return (Criteria) this;
        }

        public Criteria andLoginNotBetween(String value1, String value2) {
            addCriterion("login not between", value1, value2, "login");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNull() {
            addCriterion("passwd is null");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNotNull() {
            addCriterion("passwd is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdEqualTo(String value) {
            addCriterion("passwd =", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotEqualTo(String value) {
            addCriterion("passwd <>", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThan(String value) {
            addCriterion("passwd >", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("passwd >=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThan(String value) {
            addCriterion("passwd <", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThanOrEqualTo(String value) {
            addCriterion("passwd <=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLike(String value) {
            addCriterion("passwd like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotLike(String value) {
            addCriterion("passwd not like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdIn(List<String> values) {
            addCriterion("passwd in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotIn(List<String> values) {
            addCriterion("passwd not in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdBetween(String value1, String value2) {
            addCriterion("passwd between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotBetween(String value1, String value2) {
            addCriterion("passwd not between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andNomIsNull() {
            addCriterion("nom is null");
            return (Criteria) this;
        }

        public Criteria andNomIsNotNull() {
            addCriterion("nom is not null");
            return (Criteria) this;
        }

        public Criteria andNomEqualTo(String value) {
            addCriterion("nom =", value, "nom");
            return (Criteria) this;
        }

        public Criteria andNomNotEqualTo(String value) {
            addCriterion("nom <>", value, "nom");
            return (Criteria) this;
        }

        public Criteria andNomGreaterThan(String value) {
            addCriterion("nom >", value, "nom");
            return (Criteria) this;
        }

        public Criteria andNomGreaterThanOrEqualTo(String value) {
            addCriterion("nom >=", value, "nom");
            return (Criteria) this;
        }

        public Criteria andNomLessThan(String value) {
            addCriterion("nom <", value, "nom");
            return (Criteria) this;
        }

        public Criteria andNomLessThanOrEqualTo(String value) {
            addCriterion("nom <=", value, "nom");
            return (Criteria) this;
        }

        public Criteria andNomLike(String value) {
            addCriterion("nom like", value, "nom");
            return (Criteria) this;
        }

        public Criteria andNomNotLike(String value) {
            addCriterion("nom not like", value, "nom");
            return (Criteria) this;
        }

        public Criteria andNomIn(List<String> values) {
            addCriterion("nom in", values, "nom");
            return (Criteria) this;
        }

        public Criteria andNomNotIn(List<String> values) {
            addCriterion("nom not in", values, "nom");
            return (Criteria) this;
        }

        public Criteria andNomBetween(String value1, String value2) {
            addCriterion("nom between", value1, value2, "nom");
            return (Criteria) this;
        }

        public Criteria andNomNotBetween(String value1, String value2) {
            addCriterion("nom not between", value1, value2, "nom");
            return (Criteria) this;
        }

        public Criteria andPrenomIsNull() {
            addCriterion("prenom is null");
            return (Criteria) this;
        }

        public Criteria andPrenomIsNotNull() {
            addCriterion("prenom is not null");
            return (Criteria) this;
        }

        public Criteria andPrenomEqualTo(String value) {
            addCriterion("prenom =", value, "prenom");
            return (Criteria) this;
        }

        public Criteria andPrenomNotEqualTo(String value) {
            addCriterion("prenom <>", value, "prenom");
            return (Criteria) this;
        }

        public Criteria andPrenomGreaterThan(String value) {
            addCriterion("prenom >", value, "prenom");
            return (Criteria) this;
        }

        public Criteria andPrenomGreaterThanOrEqualTo(String value) {
            addCriterion("prenom >=", value, "prenom");
            return (Criteria) this;
        }

        public Criteria andPrenomLessThan(String value) {
            addCriterion("prenom <", value, "prenom");
            return (Criteria) this;
        }

        public Criteria andPrenomLessThanOrEqualTo(String value) {
            addCriterion("prenom <=", value, "prenom");
            return (Criteria) this;
        }

        public Criteria andPrenomLike(String value) {
            addCriterion("prenom like", value, "prenom");
            return (Criteria) this;
        }

        public Criteria andPrenomNotLike(String value) {
            addCriterion("prenom not like", value, "prenom");
            return (Criteria) this;
        }

        public Criteria andPrenomIn(List<String> values) {
            addCriterion("prenom in", values, "prenom");
            return (Criteria) this;
        }

        public Criteria andPrenomNotIn(List<String> values) {
            addCriterion("prenom not in", values, "prenom");
            return (Criteria) this;
        }

        public Criteria andPrenomBetween(String value1, String value2) {
            addCriterion("prenom between", value1, value2, "prenom");
            return (Criteria) this;
        }

        public Criteria andPrenomNotBetween(String value1, String value2) {
            addCriterion("prenom not between", value1, value2, "prenom");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurIsNull() {
            addCriterion("codetypeutilisateur is null");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurIsNotNull() {
            addCriterion("codetypeutilisateur is not null");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurEqualTo(String value) {
            addCriterion("codetypeutilisateur =", value, "codetypeutilisateur");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurNotEqualTo(String value) {
            addCriterion("codetypeutilisateur <>", value, "codetypeutilisateur");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurGreaterThan(String value) {
            addCriterion("codetypeutilisateur >", value, "codetypeutilisateur");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurGreaterThanOrEqualTo(String value) {
            addCriterion("codetypeutilisateur >=", value, "codetypeutilisateur");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurLessThan(String value) {
            addCriterion("codetypeutilisateur <", value, "codetypeutilisateur");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurLessThanOrEqualTo(String value) {
            addCriterion("codetypeutilisateur <=", value, "codetypeutilisateur");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurLike(String value) {
            addCriterion("codetypeutilisateur like", value, "codetypeutilisateur");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurNotLike(String value) {
            addCriterion("codetypeutilisateur not like", value, "codetypeutilisateur");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurIn(List<String> values) {
            addCriterion("codetypeutilisateur in", values, "codetypeutilisateur");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurNotIn(List<String> values) {
            addCriterion("codetypeutilisateur not in", values, "codetypeutilisateur");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurBetween(String value1, String value2) {
            addCriterion("codetypeutilisateur between", value1, value2, "codetypeutilisateur");
            return (Criteria) this;
        }

        public Criteria andCodetypeutilisateurNotBetween(String value1, String value2) {
            addCriterion("codetypeutilisateur not between", value1, value2, "codetypeutilisateur");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 27 22:13:31 CEST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Mon Aug 27 22:13:31 CEST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}