package fr.gbourquet.catnotab.serveur.metier.auto;

import java.io.Serializable;
import java.util.Date;

public class Personne implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catnotab.utilisateur.id
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catnotab.utilisateur.login
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    private String login;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catnotab.utilisateur.passwd
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catnotab.utilisateur.nom
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    private String nom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catnotab.utilisateur.prenom
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    private String prenom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catnotab.utilisateur.codetypeutilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    private String codetypeutilisateur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catnotab.utilisateur.dateactivation
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    private Date dateactivation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catnotab.utilisateur.datedesactivation
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    private Date datedesactivation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table catnotab.utilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catnotab.utilisateur.id
     *
     * @return the value of catnotab.utilisateur.id
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catnotab.utilisateur.id
     *
     * @param id the value for catnotab.utilisateur.id
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catnotab.utilisateur.login
     *
     * @return the value of catnotab.utilisateur.login
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catnotab.utilisateur.login
     *
     * @param login the value for catnotab.utilisateur.login
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public void setLogin(String login) {
        this.login = login == null ? null : login.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catnotab.utilisateur.passwd
     *
     * @return the value of catnotab.utilisateur.passwd
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catnotab.utilisateur.passwd
     *
     * @param passwd the value for catnotab.utilisateur.passwd
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catnotab.utilisateur.nom
     *
     * @return the value of catnotab.utilisateur.nom
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public String getNom() {
        return nom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catnotab.utilisateur.nom
     *
     * @param nom the value for catnotab.utilisateur.nom
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public void setNom(String nom) {
        this.nom = nom == null ? null : nom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catnotab.utilisateur.prenom
     *
     * @return the value of catnotab.utilisateur.prenom
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public String getPrenom() {
        return prenom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catnotab.utilisateur.prenom
     *
     * @param prenom the value for catnotab.utilisateur.prenom
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public void setPrenom(String prenom) {
        this.prenom = prenom == null ? null : prenom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catnotab.utilisateur.codetypeutilisateur
     *
     * @return the value of catnotab.utilisateur.codetypeutilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public String getCodetypeutilisateur() {
        return codetypeutilisateur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catnotab.utilisateur.codetypeutilisateur
     *
     * @param codetypeutilisateur the value for catnotab.utilisateur.codetypeutilisateur
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public void setCodetypeutilisateur(String codetypeutilisateur) {
        this.codetypeutilisateur = codetypeutilisateur == null ? null : codetypeutilisateur.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catnotab.utilisateur.dateactivation
     *
     * @return the value of catnotab.utilisateur.dateactivation
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public Date getDateactivation() {
        return dateactivation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catnotab.utilisateur.dateactivation
     *
     * @param dateactivation the value for catnotab.utilisateur.dateactivation
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public void setDateactivation(Date dateactivation) {
        this.dateactivation = dateactivation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catnotab.utilisateur.datedesactivation
     *
     * @return the value of catnotab.utilisateur.datedesactivation
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public Date getDatedesactivation() {
        return datedesactivation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catnotab.utilisateur.datedesactivation
     *
     * @param datedesactivation the value for catnotab.utilisateur.datedesactivation
     *
     * @mbggenerated Wed Aug 29 10:14:35 CEST 2012
     */
    public void setDatedesactivation(Date datedesactivation) {
        this.datedesactivation = datedesactivation;
    }
}